dinerojs/dinero.js

package.json
src/dinero.js
src/services/calculator.js
src/services/helpers.js
test/property/dinero.spec.js
test/property/helpers.spec.js
test/unit/calculator.spec.js
test/unit/dinero.spec.js
test/unit/helpers.spec.js
yarn.lock

Use [Banker's Rounding](http://wiki.c2.com/?BankersRounding) to round intermediate calculations in `#divide` and `#multiply`. Added a few property-based tests to add some robustness to the expectations and test some edge cases.
fix #11

fix(dinero): Round intermediate divide and multiply calculations

---

src/dinero.js
test/unit/dinero.spec.js

Math.round() doesn't correctly round negative values so this change first rounds the absolute value of the given amount and then multiplies in the Math.sign() afterwards.
This is my first contribution so happy for any feedback and change requests.
fix #7

fix(Update toRoundedUnit to properly round negative values)

---

.gitignore
README.md
src/dinero.js
src/services/settings.js
src/services/static.js
test/unit/dinero.spec.js

This PR adds the `precision` concept to the library (as discussed in #13). This allows user to specify how many decimal places their amount represents, so they can have more precise Dinero objects. This also provides a way to circumvent the problem raised in #9 (but this will be fixed in v2).

Add precision concept

---

CONTRIBUTING.md
docs/index.html

Replaced `npm build` with `npm run build`. It previously didn't work due to the existing [npm build command](https://docs.npmjs.com/cli/build.html).
Sorry if I have gone about this the wrong way, hopefully this is a welcome change! :)

Update to fix provided command to build dist files

---

src/dinero.js
test/unit/dinero.spec.js

Round converted amount in case converting to a smaller precision creates a float
fix #53

fix(dinero#convertPrecision): Add rounding to convertPrecision

---

README.md

Fixes a link inside the semantic-release badge, left from its markdown code probably.
(Or “Docs fix” — I wonder if it should have its own checkbox, or the “bug fix” should suffice?)

docs(readme): Fix semantic-release badge url

---

README.md

Using Dinero in our React Native app, we found that no currency symbols were showing on Android. Some digging found that newer versions of react native do not come bundled with Number.toLocaleString by default on Android, but there are instructions in the default react native project build.gradle file on how to include internationalization methods in your build, which fixed the problem for us. I thought it would be nice to include this in the readme, for others such as us who were scratching our heads as to why Dinero was working on iOS but not on Android

docs(README): add react native instructions to readme

---

src/dinero.js

fix #84
This PR documents the limitations of 64-bit floating point IEE 754 numbers.

docs: document double-precision floating-point format limitations

---

README.md

Documentation: Link to "full docs" returns a github.io 404
Changed to: https://dinerojs.com/module-dinero

docs: Update dinro-docs link

---

packages/core/src/api/compare.ts
packages/core/src/api/index.ts
packages/core/src/utils/__tests__/compare.test.ts
packages/core/src/utils/compare.ts
packages/core/src/utils/index.ts
packages/dinero.js/src/api/__tests__/compare.test.ts
packages/dinero.js/src/api/compare.ts
packages/dinero.js/src/api/index.ts
website/data/docs/api/comparisons/compare.mdx
website/data/sidebar.ts

First up - great library - v2 came along at just the right moment as we were starting to look for a good Money TS solution this week. So thank you!
This PR adds another comparison function - `compare` - to simplify sorting arrays or other collections of Dinero objects.
I did my best to implement this according to existing conventions, but I'm still new to the library, so if you're happy with the intent of this PR but need changes made, please list them all and I'll update the PR. Alternatively feel free to merge and then fix it all!
I gave an attempt at also adding docs for it - as your docs are great - but almost certainly didn't do it right, but I at least wanted to try. Again feel free to send me a list of changes to make, or merge and take care of it yourself if easier.
Finally if …

feat: add compare function

---

website/data/docs/guides/transporting-and-restoring.mdx

The unused imports caused confusion while reading the documentation, removing them might help others int the future.

docs: remove unused imports from example

---

website/data/docs/core-concepts/scale.mdx

Thank you for this library.
I believe there is an error in the docs in the example of calculating objects of different scales. I have validated this by running the code shown in the example and do indeed get a different result than what is shown there.

docs: fixes example of calculating with scale

---

website/data/docs/core-concepts/mutations.mdx
website/data/docs/core-concepts/scale.mdx

Noticed a  typo in docs  @  <a href="https://v2.dinerojs.com/docs/core-concepts/scale#:~:text=100%2C%20currency%3A%20USD%20%7D)%3B-,const%20d1,-%3D%20dinero(%7B%20amount%3A%202000000">Core concepts | Scale</a>
Also the  usage of v1 api for `allocate` @  <a target="_blank" href="https://v2.dinerojs.com/docs/core-concepts/mutations#:~:text=USD%20%7D)%0A)%3B%0A%0Aconst%20%5Bdiscount%5D%20%3D-,allocate,-(%5B20%2C%2080%5D)%3B%0Aconst">Core concepts | Mutations</a>

fix(docs): correct typo & update code snippet

---

packages/core/src/helpers/createDinero.ts
packages/dinero.js/src/__tests__/dinero.test.ts

In order to save and retrieve dineros to/from our storage layer we map them to a copycat money-type. However, on retrievals we noticed that internal fields were leaking into the currency objects like so:
```
"amount": 0,
"currency": {
"_type": "currencyObj",  <----
"base": 10,
"code": "USD",
"exponent": 2
},
"scale": 2
```
... and upon further investigation one can pass anything into a dinero's currency object as long as the required subset of fields is met. This change makes the selection of fields as explicit as the base structure's (where `amount`, `currency` and `scale` are taken and everything else ignored).

fix: don't accept extra fields inside the currency options on create

---

packages/calculator-bigint/tsconfig.json
packages/calculator-number/tsconfig.json
packages/core/tsconfig.json
packages/currencies/tsconfig.json
packages/dinero.js/tsconfig.json

I added an exclude directive to the `tsconfig.json` files in the packages.
@sarahdayan wIth this change, I get type errors in my editor for tests files, and the `test:types` fails if there is a type error in a test. Though it doesn't attempt to build the tests, which is why the build is currently failing.

build: fix build failure because of type checking tests

---

api-extractor.json
packages/calculator-bigint/tsconfig.declaration.json
packages/calculator-bigint/tsconfig.json
packages/calculator-number/tsconfig.declaration.json
packages/calculator-number/tsconfig.json
packages/core/tsconfig.declaration.json
packages/core/tsconfig.json
packages/currencies/tsconfig.declaration.json
packages/currencies/tsconfig.json
packages/dinero.js/tsconfig.declaration.json
packages/dinero.js/tsconfig.json
tsconfig.declaration.json
tsconfig.json

Update `api-extractor.json` after learning more about it.
- use `overrideTsconfig` to eliminate the need for `tsconfig.declaration.json` files in the projects
- add `"newlineKind": "lf"` to fix line ending issue

refactor: api-extractor config

---

.prettierignore
packages/calculator-bigint/etc/calculator-bigint.api.md
packages/calculator-number/etc/calculator-number.api.md
packages/core/etc/core.api.md
packages/dinero.js/etc/dinero.js.api.md

I finally figured out why the `*.api.md` files kept being reformatted! `api-extractor` uses the code in the `lib` folder to build the api files, but it wasn't ignored by Prettier so anytime the script `format` ran it would format all the files in the lib folders, then on the next run of `build:types` the reformatted code was used!
- Add `lib` to `.prettierignore`
- Rebuild all the `*.api.md` files to original output from `api-extractor`
Now the `*.api.md` files should only change if the api does.

build: stop formatting api files

---

src/services/helpers.js
test/unit/dinero.spec.js

It was fixed by adding a condition that verifies if ratio is numeric and has number type in areValidRatios function. 
fixes #588

fix: prevent string input to be used in allocate function

---

packages/core/src/api/toDecimal.ts
packages/dinero.js/src/api/__tests__/toDecimal.test.ts

Previously, toDecimal would format an amount like -1050 as '-10.-50', when we'd expect '-10.50'. We now use the absolute value of all but the first unit when building the decimal string.

fix(toDecimal): teach `toDecimal` how to handle negative units

---

packages/core/src/api/toDecimal.ts
packages/dinero.js/src/api/__tests__/toDecimal.test.ts

Change #690 fixed the general case of formatting negative unit values, but was one remaining case where formatting was still incorrect: when the first unit is -0, the resulting string didn't include the leading negative sign.
This change identifies that exact case (negative value, leading zero) and pads the resulting string with a leading negative sign.
Fixes #692

fix(toDecimal): preserve negative sign for leading zeros

---

turbo.json

@sarahdayan turbo wasn't caching the `.next` directory. So when it tried to use the cache it would fail. I think this should do it!

build: add `.next` directory to Turborepo build outputs

---

.circleci/config.yml

The old `circleci` convenience Docker images have been [deprecated](https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034) for over a year. This updates the Node.js image with the [next-gen CircleCI convenience images](https://circleci.com/blog/announcing-our-next-generation-convenience-images-smaller-faster-more-deterministic/).

ci: update Docker image

---

scripts/build-types.mjs
scripts/lint.mjs
scripts/test.mjs
scripts/utils/exec.mjs

The previous behavior was to reject an Error if the command being executed returned a non zero exit code. Though all the stderr output was already passed through, and the rejected error wasn't handled so it caused an unhandled promise rejection, which left unhelpful noise in the build output log.
Also, modified the JSDoc comments to follow the ESLint rule `jsdoc/require-description-complete-sentence`.

refactor(exec): resolve/reject exit code

---

package.json
packages/core/etc/core.api.md
packages/core/src/divide/__tests__/down.test.ts
packages/core/src/divide/__tests__/halfAwayFromZero.test.ts
packages/core/src/divide/__tests__/halfDown.test.ts
packages/core/src/divide/__tests__/halfEven.test.ts
packages/core/src/divide/__tests__/halfOdd.test.ts
packages/core/src/divide/__tests__/halfTowardsZero.test.ts
packages/core/src/divide/__tests__/halfUp.test.ts
packages/core/src/divide/__tests__/up.test.ts
packages/core/src/divide/down.ts
packages/core/src/divide/halfAwayFromZero.ts
packages/core/src/divide/halfDown.ts
packages/core/src/divide/halfEven.ts
packages/core/src/divide/halfOdd.ts
packages/core/src/divide/halfTowardsZero.ts
packages/core/src/divide/halfUp.ts
packages/core/src/divide/up.ts
packages/dinero.js/src/api/__tests__/multiply.test.ts
yarn.lock

up/down - Functions should not round integer results.
up - up should only round positive numbers, 0 is not a positive number.
halfUp - halfUp was incorrectly rounding numbers in the [0,1) range due to the incorrect definition of isPositive.
Fixes #710
Fixes #713
Written by throwing tests at the wall and making them pass, would appreciate if someone could review their correctness.
In the rounding functions, is it necessary to handle the case where factor is negative? If so, the definition of isPositive in some of the functions may not handle this case.
From a big picture going to beta POV, some of these rounding functions are really obscure (e.g. halfOdd) and have little practical application. They also feel non-trivial to get right, do we really need all of them?
Also, rounding to -0 is …

fix(up, down, halfUp): fix handling of numbers close to 0 and rounding of integer results

---

test/tsconfig.json

The `test/tsconfig.json` extended a nonexistent `tsconfig.test`. It now extends the root `tsconfig.json`.

test: fix test/tsconfig.json extends property

---

packages/core/src/api/isPositive.ts
packages/dinero.js/src/api/__tests__/isNegative.test.ts
packages/dinero.js/src/api/__tests__/isPositive.test.ts
website/data/docs/api/comparisons/is-positive.mdx

The function `isPositive` should return `false` when passing Dinero objects with amount `0` or `-0`, as zero is unsigned—neither negative nor positive.

fix(isPositive): return `false` with zero
